/* Generated by re2c 2.2 */
#include <string.h>
#include "cmd.h"





LineStatus lexLines(Input *in)
{

	char yych;
	unsigned yyaccept;
	LineStatus ret = BAD_LINE;
	in->text_f = in->text_s = in->cur;

	#define YYGETSTATE in->state
	switch (YYGETSTATE) {
default:
	goto yy0;
case 0:
	if (in->lim <= in->cur) goto yy33;
	goto yyFillLabel0;
case 1:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel1;
case 2:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel2;
case 3:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel3;
case 4:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel4;
case 5:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel5;
case 6:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel6;
case 7:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel7;
case 8:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel8;
case 9:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel9;
case 10:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel10;
case 11:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel11;
case 12:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel12;
case 13:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel13;
case 14:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel14;
case 15:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel15;
case 16:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel16;
case 17:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel17;
case 18:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel18;
case 19:
	if (in->lim <= in->cur) goto yy11;
	goto yyFillLabel19;
case 20:
	if (in->lim <= in->cur) goto yy41;
	goto yyFillLabel20;
case 21:
	if (in->lim <= in->cur) goto yy37;
	goto yyFillLabel21;
case 22:
	if (in->lim <= in->cur) goto yy54;
	goto yyFillLabel22;
case 23:
	if (in->lim <= in->cur) goto yy46;
	goto yyFillLabel23;
case 24:
	if (in->lim <= in->cur) goto yy48;
	goto yyFillLabel24;
case 25:
	if (in->lim <= in->cur) goto yy65;
	goto yyFillLabel25;
case 26:
	if (in->lim <= in->cur) goto yy59;
	goto yyFillLabel26;
case 27:
	if (in->lim <= in->cur) goto yy61;
	goto yyFillLabel27;
}

	#undef YYGETSTATE

	for(;;) {
	in->mar = in->cur;
	

yy0:
	switch (in->cond) {
	case yycinit:
		goto yyc_init;
	case yycbad:
		goto yyc_bad;
	case yyctext:
		goto yyc_text;
	case yycskip:
		goto yyc_skip;
	}
/* *********************************** */
yyc_init:
yyFillLabel0:
	yych = *in->cur;
	switch (yych) {
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 0;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy5;
	case 'E':
	case 'e':	goto yy6;
	case 'G':
	case 'g':	goto yy7;
	default:	goto yy3;
	}
yy3:
	++in->cur;
yy4:
	in->cond = yycbad;
	{ ret = BAD_LINE; break; }
yy5:
	++in->cur;
yyFillLabel1:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy8;
	default:
		if (in->lim <= in->cur) {
			in->state = 1;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy4;
	}
yy6:
	in->mar = ++in->cur;
yyFillLabel2:
	yych = *in->cur;
	switch (yych) {
	case 'C':
	case 'c':	goto yy10;
	default:
		if (in->lim <= in->cur) {
			in->state = 2;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy4;
	}
yy7:
	in->mar = ++in->cur;
yyFillLabel3:
	yych = *in->cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy12;
	default:
		if (in->lim <= in->cur) {
			in->state = 3;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy4;
	}
yy8:
	++in->cur;
	{ ret = BAD_LINE; break; }
yy10:
	++in->cur;
yyFillLabel4:
	yych = *in->cur;
	switch (yych) {
	case 'H':
	case 'h':	goto yy13;
	default:
		if (in->lim <= in->cur) {
			in->state = 4;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy11:
	in->cur = in->mar;
	goto yy4;
yy12:
	++in->cur;
yyFillLabel5:
	yych = *in->cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy14;
	default:
		if (in->lim <= in->cur) {
			in->state = 5;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy13:
	++in->cur;
yyFillLabel6:
	yych = *in->cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy15;
	default:
		if (in->lim <= in->cur) {
			in->state = 6;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy14:
	++in->cur;
yyFillLabel7:
	yych = *in->cur;
	switch (yych) {
	case ' ':	goto yy16;
	default:
		if (in->lim <= in->cur) {
			in->state = 7;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy15:
	++in->cur;
yyFillLabel8:
	yych = *in->cur;
	switch (yych) {
	case ' ':	goto yy17;
	default:
		if (in->lim <= in->cur) {
			in->state = 8;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy16:
	++in->cur;
yyFillLabel9:
	yych = *in->cur;
	switch (yych) {
	case 'D':
	case 'd':	goto yy19;
	case 'T':
	case 't':	goto yy20;
	default:
		if (in->lim <= in->cur) {
			in->state = 9;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy17:
	++in->cur;
	in->cond = yyctext;
	{ in->text_f = in->text_s = in->cur; continue; }
yy19:
	++in->cur;
yyFillLabel10:
	yych = *in->cur;
	switch (yych) {
	case 'A':
	case 'a':	goto yy21;
	default:
		if (in->lim <= in->cur) {
			in->state = 10;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy20:
	++in->cur;
yyFillLabel11:
	yych = *in->cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy22;
	default:
		if (in->lim <= in->cur) {
			in->state = 11;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy21:
	++in->cur;
yyFillLabel12:
	yych = *in->cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy23;
	default:
		if (in->lim <= in->cur) {
			in->state = 12;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy22:
	++in->cur;
yyFillLabel13:
	yych = *in->cur;
	switch (yych) {
	case 'M':
	case 'm':	goto yy24;
	default:
		if (in->lim <= in->cur) {
			in->state = 13;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy23:
	++in->cur;
yyFillLabel14:
	yych = *in->cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy25;
	default:
		if (in->lim <= in->cur) {
			in->state = 14;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy24:
	++in->cur;
yyFillLabel15:
	yych = *in->cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy26;
	default:
		if (in->lim <= in->cur) {
			in->state = 15;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy25:
	++in->cur;
yyFillLabel16:
	yych = *in->cur;
	switch (yych) {
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 16;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy27;
	default:	goto yy11;
	}
yy26:
	++in->cur;
yyFillLabel17:
	yych = *in->cur;
	switch (yych) {
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 17;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy28;
	default:	goto yy11;
	}
yy27:
	++in->cur;
yyFillLabel18:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy29;
	default:
		if (in->lim <= in->cur) {
			in->state = 18;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy28:
	++in->cur;
yyFillLabel19:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy31;
	default:
		if (in->lim <= in->cur) {
			in->state = 19;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy11;
	}
yy29:
	++in->cur;
	{ ret = DATE; break; }
yy31:
	++in->cur;
	{ ret = TIME; break; }
yy33:
	{ return WAITING; }
/* *********************************** */
yyc_bad:
yyFillLabel20:
	yych = *in->cur;
	switch (yych) {
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 20;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy38;
	default:	goto yy36;
	}
yy36:
	++in->cur;
yy37:
	{ continue; }
yy38:
	++in->cur;
yyFillLabel21:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy39;
	default:
		if (in->lim <= in->cur) {
			in->state = 21;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy37;
	}
yy39:
	++in->cur;
	in->cond = yycinit;
	{ continue; }
yy41:
	{ return WAITING; }
/* *********************************** */
yyc_text:
yyFillLabel22:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\v':
	case '\f':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy44;
	case '\n':	goto yy47;
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 22;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy49;
	default:	goto yy50;
	}
yy44:
	++in->cur;
yyFillLabel23:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\v':
	case '\f':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy44;
	default:
		if (in->lim <= in->cur) {
			in->state = 23;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy46;
	}
yy46:
	{ in->text_f = in->cur; continue; }
yy47:
	++in->cur;
yy48:
	{ in->text_f = in->cur; continue; }
yy49:
	++in->cur;
yyFillLabel24:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy52;
	default:
		if (in->lim <= in->cur) {
			in->state = 24;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy48;
	}
yy50:
	++in->cur;
	in->cond = yycskip;
	{ ret = PARTIAL_ECHO; break; }
yy52:
	++in->cur;
	in->cond = yycinit;
	{ ret = ECHO; break; }
yy54:
	{ return WAITING; }
/* *********************************** */
yyc_skip:
yyFillLabel25:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy60;
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 25;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy62;
	default:	goto yy57;
	}
yy57:
	++in->cur;
yyFillLabel26:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':
		if (in->lim <= in->cur) {
			in->state = 26;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy59;
	default:	goto yy57;
	}
yy59:
	{ continue; }
yy60:
	++in->cur;
yy61:
	{ continue; }
yy62:
	++in->cur;
yyFillLabel27:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy63;
	default:
		if (in->lim <= in->cur) {
			in->state = 27;
			{ if(in->cond != yycinit) in->mar = in->cur; if(in->cond == yyctext) { in->text_f = in->cur; return PARTIAL_ECHO; } else return WAITING; }
		}
		goto yy61;
	}
yy63:
	++in->cur;
	in->cond = yycinit;
	{ ret = ECHO; break; }
yy65:
	{ return WAITING; }

	}

	in->state = -1;
	return ret;
}

DatagramStatus lexDatagram(const char *str, size_t len)
{
	const char *YYCURSOR = str,	 *YYLIMIT = str + len, *YYMARKER;
	char yych;
	DatagramStatus result = BAD_DATAGRAM;

	for(;;)
	{
	

yyFillLabel28:
	yych = *YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy71;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy69;
	}
yy69:
	++YYCURSOR;
yy70:
	{ return BAD_DATAGRAM; }
yy71:
	YYMARKER = ++YYCURSOR;
yyFillLabel29:
	yych = *YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy72;
	case 'T':
	case 't':	goto yy74;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy70;
	}
yy72:
	++YYCURSOR;
yyFillLabel30:
	yych = *YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy75;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy73:
	YYCURSOR = YYMARKER;
	goto yy70;
yy74:
	++YYCURSOR;
yyFillLabel31:
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy76;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy75:
	++YYCURSOR;
yyFillLabel32:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy77;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy76:
	++YYCURSOR;
yyFillLabel33:
	yych = *YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy78;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy77:
	++YYCURSOR;
yyFillLabel34:
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy79;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy78:
	++YYCURSOR;
yyFillLabel35:
	yych = *YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy80;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy79:
	++YYCURSOR;
yyFillLabel36:
	yych = *YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy82;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy80:
	++YYCURSOR;
	{ result = STATS; continue; }
yy82:
	++YYCURSOR;
yyFillLabel37:
	yych = *YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy83;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy83:
	++YYCURSOR;
yyFillLabel38:
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy84;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy84:
	++YYCURSOR;
yyFillLabel39:
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy85;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy85:
	++YYCURSOR;
yyFillLabel40:
	yych = *YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy86;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy86:
	++YYCURSOR;
yyFillLabel41:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy87;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy87:
	++YYCURSOR;
yyFillLabel42:
	yych = *YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy88;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy88:
	++YYCURSOR;
yyFillLabel43:
	yych = *YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy89;
	case 'S':
	case 's':	goto yy91;
	default:
		if (YYLIMIT <= YYCURSOR) {
			
			return result;
		}
		goto yy73;
	}
yy89:
	++YYCURSOR;
	{ result = LOCALE_EN; continue; }
yy91:
	++YYCURSOR;
	{ result = LOCALE_ES; continue; }
yy93:
	{ return result; }

	}

	return BAD_DATAGRAM;
}
