/* Generated by re2c 2.2 */

#pragma once
#include "lexer.h"
enum YYCONDTYPE {
	yycinit,
	yycbad,
	yyctext,
	yycskip,
};

LineStatus lexLines(Input *in);
DatagramStatus lexDatagram(const char *str, size_t len);
