/* Generated by re2c 2.2 */
#include "logger.h"
#include "pop3.h"
#include <stdbool.h>
#include <string.h>



#define COPY                                                                                                           \
	do                                                                                                                 \
	{                                                                                                                  \
		memcpy(&in->writeBuf[in->written], in->tok, in->cur - in->tok);                                                \
		in->written += in->cur - in->tok;                                                                              \
	} while (0)

bool destuffMail(Input *in)
{
	char yych;
	bool result;

#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy0;
case 0:
	if (in->lim <= in->cur) goto yy15;
	goto yyFillLabel0;
case 1:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel1;
case 2:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel2;
case 3:
	if (in->lim <= in->cur) goto yy10;
	goto yyFillLabel3;
case 4:
	if (in->lim <= in->cur) goto yy26;
	goto yyFillLabel4;
case 5:
	if (in->lim <= in->cur) goto yy20;
	goto yyFillLabel5;
case 6:
	if (in->lim <= in->cur) goto yy22;
	goto yyFillLabel6;
}

#undef YYGETSTATE

	for (;;)
	{
		in->tok = in->mar = in->cur;
		

yy0:
	switch (in->cond) {
	case yycbegin:
		goto yyc_begin;
	case yycline:
		goto yyc_line;
	}
/* *********************************** */
yyc_begin:
yyFillLabel0:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy5;
	case '.':	goto yy6;
	default:
		if (in->lim <= in->cur) {
			in->state = 0;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy3;
	}
yy3:
	++in->cur;
yy4:
	in->cond = yycline;
	{ COPY; continue; }
yy5:
	++in->cur;
yyFillLabel1:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy7;
	default:
		if (in->lim <= in->cur) {
			in->state = 1;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy4;
	}
yy6:
	in->mar = ++in->cur;
yyFillLabel2:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy9;
	case '.':	goto yy11;
	default:
		if (in->lim <= in->cur) {
			in->state = 2;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy4;
	}
yy7:
	++in->cur;
	{ COPY; continue; }
yy9:
	++in->cur;
yyFillLabel3:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy13;
	default:
		if (in->lim <= in->cur) {
			in->state = 3;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy10;
	}
yy10:
	in->cur = in->mar;
	goto yy4;
yy11:
	++in->cur;
	in->cond = yycline;
	{ in->writeBuf[in->written++] = '.'; continue; }
yy13:
	++in->cur;
	{ result = true; break; }
yy15:
	{ result = true; break; }
/* *********************************** */
yyc_line:
yyFillLabel4:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy21;
	case '\r':	goto yy23;
	default:
		if (in->lim <= in->cur) {
			in->state = 4;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy18;
	}
yy18:
	++in->cur;
yyFillLabel5:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy20;
	default:
		if (in->lim <= in->cur) {
			in->state = 5;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy18;
	}
yy20:
	{ COPY; continue; }
yy21:
	++in->cur;
yy22:
	{ COPY; continue; }
yy23:
	++in->cur;
yyFillLabel6:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy24;
	default:
		if (in->lim <= in->cur) {
			in->state = 6;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy22;
	}
yy24:
	++in->cur;
	in->cond = yycbegin;
	{ COPY; continue; }
yy26:
	{ result = true; break; }

	}

	in->state = -1;
	return result;
}

bool stuffMail(Input *in)
{
	char yych;
	bool result;

#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy27;
case 7:
	if (in->lim <= in->cur) goto yy37;
	goto yyFillLabel7;
case 8:
	if (in->lim <= in->cur) goto yy31;
	goto yyFillLabel8;
case 9:
	if (in->lim <= in->cur) goto yy48;
	goto yyFillLabel9;
case 10:
	if (in->lim <= in->cur) goto yy42;
	goto yyFillLabel10;
case 11:
	if (in->lim <= in->cur) goto yy44;
	goto yyFillLabel11;
}

#undef YYGETSTATE

	for (;;)
	{
		in->tok = in->mar = in->cur;
		

yy27:
	switch (in->cond) {
	case yycbegin:
		goto yyc_begin;
	case yycline:
		goto yyc_line;
	}
/* *********************************** */
yyc_begin:
yyFillLabel7:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy32;
	case '.':	goto yy33;
	default:
		if (in->lim <= in->cur) {
			in->state = 7;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy30;
	}
yy30:
	++in->cur;
yy31:
	in->cond = yycline;
	{ COPY; continue; }
yy32:
	++in->cur;
yyFillLabel8:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy35;
	default:
		if (in->lim <= in->cur) {
			in->state = 8;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy31;
	}
yy33:
	++in->cur;
	in->cond = yycline;
	{ in->writeBuf[in->written++] = '.'; in->writeBuf[in->written++] = '.'; continue; }
yy35:
	++in->cur;
	{ COPY; continue; }
yy37:
	{ char str[] = ".\r\n"; memcpy(&in->writeBuf[in->written], str, sizeof(str) - 1); in->written += sizeof(str) - 1; result = true; break; }
/* *********************************** */
yyc_line:
yyFillLabel9:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy43;
	case '\r':	goto yy45;
	default:
		if (in->lim <= in->cur) {
			in->state = 9;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy40;
	}
yy40:
	++in->cur;
yyFillLabel10:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy42;
	default:
		if (in->lim <= in->cur) {
			in->state = 10;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy40;
	}
yy42:
	{ COPY; continue; }
yy43:
	++in->cur;
yy44:
	{ COPY; continue; }
yy45:
	++in->cur;
yyFillLabel11:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy46;
	default:
		if (in->lim <= in->cur) {
			in->state = 11;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy44;
	}
yy46:
	++in->cur;
	in->cond = yycbegin;
	{ COPY; continue; }
yy48:
	{ char str[] = ".\r\n"; memcpy(&in->writeBuf[in->written], str, sizeof(str) - 1); in->written += sizeof(str) - 1; result = true; break; }

	}

	in->state = -1;
	return result;
}

bool parsePopResponse(Input *in, bool multiline, bool *success)
{
	char yych;
	bool result;

#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy49;
case 12:
	if (in->lim <= in->cur) goto yy64;
	goto yyFillLabel12;
case 13:
	if (in->lim <= in->cur) goto yy53;
	goto yyFillLabel13;
case 14:
	if (in->lim <= in->cur) goto yy53;
	goto yyFillLabel14;
case 15:
	if (in->lim <= in->cur) goto yy57;
	goto yyFillLabel15;
case 16:
	if (in->lim <= in->cur) goto yy57;
	goto yyFillLabel16;
case 17:
	if (in->lim <= in->cur) goto yy57;
	goto yyFillLabel17;
case 18:
	if (in->lim <= in->cur) goto yy75;
	goto yyFillLabel18;
case 19:
	if (in->lim <= in->cur) goto yy69;
	goto yyFillLabel19;
case 20:
	if (in->lim <= in->cur) goto yy71;
	goto yyFillLabel20;
case 21:
	if (in->lim <= in->cur) goto yy86;
	goto yyFillLabel21;
case 22:
	if (in->lim <= in->cur) goto yy80;
	goto yyFillLabel22;
case 23:
	if (in->lim <= in->cur) goto yy82;
	goto yyFillLabel23;
case 24:
	if (in->lim <= in->cur) goto yy101;
	goto yyFillLabel24;
case 25:
	if (in->lim <= in->cur) goto yy91;
	goto yyFillLabel25;
case 26:
	if (in->lim <= in->cur) goto yy93;
	goto yyFillLabel26;
case 27:
	if (in->lim <= in->cur) goto yy96;
	goto yyFillLabel27;
case 28:
	if (in->lim <= in->cur) goto yy96;
	goto yyFillLabel28;
case 29:
	if (in->lim <= in->cur) goto yy96;
	goto yyFillLabel29;
}

#undef YYGETSTATE

	for (;;)
	{
		in->tok = in->mar = in->cur;
		

yy49:
	switch (in->cond) {
	case yycstatus:
		goto yyc_status;
	case yycmsg_err:
		goto yyc_msg_err;
	case yycmsg_ok:
		goto yyc_msg_ok;
	case yycextra:
		goto yyc_extra;
	}
/* *********************************** */
yyc_status:
yyFillLabel12:
	yych = *in->cur;
	switch (yych) {
	case '+':	goto yy54;
	case '-':	goto yy55;
	default:
		if (in->lim <= in->cur) {
			in->state = 12;
			{ return false; }
		}
		goto yy52;
	}
yy52:
	++in->cur;
yy53:
	{ char str[] = "-ERR Invalid response from origin\r\n"; memcpy(&in->writeBuf[in->written], str, sizeof(str) - 1); in->written += sizeof(str) - 1; result = true; break; }
yy54:
	in->mar = ++in->cur;
yyFillLabel13:
	yych = *in->cur;
	switch (yych) {
	case 'O':	goto yy56;
	default:
		if (in->lim <= in->cur) {
			in->state = 13;
			{ return false; }
		}
		goto yy53;
	}
yy55:
	in->mar = ++in->cur;
yyFillLabel14:
	yych = *in->cur;
	switch (yych) {
	case 'E':	goto yy58;
	default:
		if (in->lim <= in->cur) {
			in->state = 14;
			{ return false; }
		}
		goto yy53;
	}
yy56:
	++in->cur;
yyFillLabel15:
	yych = *in->cur;
	switch (yych) {
	case 'K':	goto yy59;
	default:
		if (in->lim <= in->cur) {
			in->state = 15;
			{ return false; }
		}
		goto yy57;
	}
yy57:
	in->cur = in->mar;
	goto yy53;
yy58:
	++in->cur;
yyFillLabel16:
	yych = *in->cur;
	switch (yych) {
	case 'R':	goto yy61;
	default:
		if (in->lim <= in->cur) {
			in->state = 16;
			{ return false; }
		}
		goto yy57;
	}
yy59:
	++in->cur;
	in->cond = yycmsg_ok;
	{ COPY; *success = true; continue; }
yy61:
	++in->cur;
yyFillLabel17:
	yych = *in->cur;
	switch (yych) {
	case 'R':	goto yy62;
	default:
		if (in->lim <= in->cur) {
			in->state = 17;
			{ return false; }
		}
		goto yy57;
	}
yy62:
	++in->cur;
	in->cond = yycmsg_err;
	{ COPY; *success = false; continue; }
yy64:
	{ result = true; break; }
/* *********************************** */
yyc_msg_err:
yyFillLabel18:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy70;
	case '\r':	goto yy72;
	default:
		if (in->lim <= in->cur) {
			in->state = 18;
			{ return false; }
		}
		goto yy67;
	}
yy67:
	++in->cur;
yyFillLabel19:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy69;
	default:
		if (in->lim <= in->cur) {
			in->state = 19;
			{ return false; }
		}
		goto yy67;
	}
yy69:
	{ COPY; continue; }
yy70:
	++in->cur;
yy71:
	{ COPY; continue; }
yy72:
	++in->cur;
yyFillLabel20:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy73;
	default:
		if (in->lim <= in->cur) {
			in->state = 20;
			{ return false; }
		}
		goto yy71;
	}
yy73:
	++in->cur;
	{ COPY; result = true; break; }
yy75:
	{ result = true; break; }
/* *********************************** */
yyc_msg_ok:
yyFillLabel21:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy81;
	case '\r':	goto yy83;
	default:
		if (in->lim <= in->cur) {
			in->state = 21;
			{ return false; }
		}
		goto yy78;
	}
yy78:
	++in->cur;
yyFillLabel22:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	default:
		if (in->lim <= in->cur) {
			in->state = 22;
			{ return false; }
		}
		goto yy78;
	}
yy80:
	{ COPY; continue; }
yy81:
	++in->cur;
yy82:
	{ COPY; continue; }
yy83:
	++in->cur;
yyFillLabel23:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy84;
	default:
		if (in->lim <= in->cur) {
			in->state = 23;
			{ return false; }
		}
		goto yy82;
	}
yy84:
	++in->cur;
	{ COPY; if(multiline) { in->cond = yycextra; continue; } else { result = true; break; } }
yy86:
	{ result = true; break; }
/* *********************************** */
yyc_extra:
yyFillLabel24:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy92;
	case '\r':	goto yy94;
	default:
		if (in->lim <= in->cur) {
			in->state = 24;
			{ return false; }
		}
		goto yy89;
	}
yy89:
	++in->cur;
yyFillLabel25:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy91;
	default:
		if (in->lim <= in->cur) {
			in->state = 25;
			{ return false; }
		}
		goto yy89;
	}
yy91:
	{ COPY; continue; }
yy92:
	++in->cur;
yy93:
	{ COPY; continue; }
yy94:
	in->mar = ++in->cur;
yyFillLabel26:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy95;
	default:
		if (in->lim <= in->cur) {
			in->state = 26;
			{ return false; }
		}
		goto yy93;
	}
yy95:
	++in->cur;
yyFillLabel27:
	yych = *in->cur;
	switch (yych) {
	case '.':	goto yy97;
	default:
		if (in->lim <= in->cur) {
			in->state = 27;
			{ return false; }
		}
		goto yy96;
	}
yy96:
	in->cur = in->mar;
	goto yy93;
yy97:
	++in->cur;
yyFillLabel28:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy98;
	default:
		if (in->lim <= in->cur) {
			in->state = 28;
			{ return false; }
		}
		goto yy96;
	}
yy98:
	++in->cur;
yyFillLabel29:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy99;
	default:
		if (in->lim <= in->cur) {
			in->state = 29;
			{ return false; }
		}
		goto yy96;
	}
yy99:
	++in->cur;
	{ COPY; result = true; break; }
yy101:
	{ result = true; break; }

	}

	*success = in->cond == yycmsg_ok || in->cond == yycextra;
	in->tok = in->mar = in->cur;
	in->state = -1;
	in->cond = yycstatus;
	return result;
}

PopCommand parsePopRequest(Input *in, char **arg, size_t *argLen, size_t *len)
{
	char yych;
	char *args = NULL, *arge = NULL, *end;
	PopCommand result;
	#define yyt1 in->yyt1
#define yyt2 in->yyt2


#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy102;
case 30:
	if (in->lim <= in->cur) goto yy224;
	goto yyFillLabel30;
case 31:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel31;
case 32:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel32;
case 33:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel33;
case 34:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel34;
case 35:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel35;
case 36:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel36;
case 37:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel37;
case 38:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel38;
case 39:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel39;
case 40:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel40;
case 41:
	if (in->lim <= in->cur) goto yy106;
	goto yyFillLabel41;
case 42:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel42;
case 43:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel43;
case 44:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel44;
case 45:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel45;
case 46:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel46;
case 47:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel47;
case 48:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel48;
case 49:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel49;
case 50:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel50;
case 51:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel51;
case 52:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel52;
case 53:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel53;
case 54:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel54;
case 55:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel55;
case 56:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel56;
case 57:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel57;
case 58:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel58;
case 59:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel59;
case 60:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel60;
case 61:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel61;
case 62:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel62;
case 63:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel63;
case 64:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel64;
case 65:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel65;
case 66:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel66;
case 67:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel67;
case 68:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel68;
case 69:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel69;
case 70:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel70;
case 71:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel71;
case 72:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel72;
case 73:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel73;
case 74:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel74;
case 75:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel75;
case 76:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel76;
case 77:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel77;
case 78:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel78;
case 79:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel79;
case 80:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel80;
case 81:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel81;
case 82:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel82;
case 83:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel83;
case 84:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel84;
case 85:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel85;
case 86:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel86;
case 87:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel87;
case 88:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel88;
case 89:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel89;
case 90:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel90;
case 91:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel91;
case 92:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel92;
case 93:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel93;
case 94:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel94;
case 95:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel95;
case 96:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel96;
case 97:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel97;
case 98:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel98;
case 99:
	if (in->lim <= in->cur) goto yy121;
	goto yyFillLabel99;
}

#undef YYGETSTATE

	for (;;)
	{
		

yy102:
yyFillLabel30:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy107;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'O':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'o':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy108;
	case 'C':
	case 'c':	goto yy109;
	case 'D':
	case 'd':	goto yy110;
	case 'L':
	case 'l':	goto yy111;
	case 'N':
	case 'n':	goto yy112;
	case 'P':
	case 'p':	goto yy113;
	case 'Q':
	case 'q':	goto yy114;
	case 'R':
	case 'r':	goto yy115;
	case 'S':
	case 's':	goto yy116;
	case 'U':
	case 'u':	goto yy117;
	default:
		if (in->lim <= in->cur) {
			in->state = 30;
			{ return POP_INCOMPLETE; }
		}
		goto yy105;
	}
yy105:
	++in->cur;
yy106:
	{ result = POP_INVALID; break; }
yy107:
	++in->cur;
yyFillLabel31:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy118;
	default:
		if (in->lim <= in->cur) {
			in->state = 31;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy108:
	in->mar = ++in->cur;
yyFillLabel32:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 32;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy109:
	in->mar = ++in->cur;
yyFillLabel33:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'A':
	case 'a':	goto yy124;
	default:
		if (in->lim <= in->cur) {
			in->state = 33;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy110:
	in->mar = ++in->cur;
yyFillLabel34:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'E':
	case 'e':	goto yy125;
	default:
		if (in->lim <= in->cur) {
			in->state = 34;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy111:
	in->mar = ++in->cur;
yyFillLabel35:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'I':
	case 'i':	goto yy126;
	default:
		if (in->lim <= in->cur) {
			in->state = 35;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy112:
	in->mar = ++in->cur;
yyFillLabel36:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'O':
	case 'o':	goto yy127;
	default:
		if (in->lim <= in->cur) {
			in->state = 36;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy113:
	in->mar = ++in->cur;
yyFillLabel37:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'A':
	case 'a':	goto yy128;
	default:
		if (in->lim <= in->cur) {
			in->state = 37;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy114:
	in->mar = ++in->cur;
yyFillLabel38:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'U':
	case 'u':	goto yy129;
	default:
		if (in->lim <= in->cur) {
			in->state = 38;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy115:
	in->mar = ++in->cur;
yyFillLabel39:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'E':
	case 'e':	goto yy130;
	case 'S':
	case 's':	goto yy131;
	default:
		if (in->lim <= in->cur) {
			in->state = 39;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy116:
	in->mar = ++in->cur;
yyFillLabel40:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'T':
	case 't':	goto yy132;
	default:
		if (in->lim <= in->cur) {
			in->state = 40;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy117:
	in->mar = ++in->cur;
yyFillLabel41:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	case 'S':
	case 's':	goto yy133;
	default:
		if (in->lim <= in->cur) {
			in->state = 41;
			{ return POP_INCOMPLETE; }
		}
		goto yy106;
	}
yy118:
	++in->cur;
	{ result = POP_INVALID; break; }
yy120:
	++in->cur;
yyFillLabel42:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy134;
	default:
		if (in->lim <= in->cur) {
			in->state = 42;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy121:
	in->cur = in->mar;
	goto yy106;
yy122:
	++in->cur;
yyFillLabel43:
	yych = *in->cur;
yy123:
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 43;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy124:
	++in->cur;
yyFillLabel44:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 44;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'P':
	case 'p':	goto yy136;
	default:	goto yy123;
	}
yy125:
	++in->cur;
yyFillLabel45:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 45;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'L':
	case 'l':	goto yy137;
	default:	goto yy123;
	}
yy126:
	++in->cur;
yyFillLabel46:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 46;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'S':
	case 's':	goto yy138;
	default:	goto yy123;
	}
yy127:
	++in->cur;
yyFillLabel47:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 47;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'O':
	case 'o':	goto yy139;
	default:	goto yy123;
	}
yy128:
	++in->cur;
yyFillLabel48:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 48;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'S':
	case 's':	goto yy140;
	default:	goto yy123;
	}
yy129:
	++in->cur;
yyFillLabel49:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 49;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'I':
	case 'i':	goto yy141;
	default:	goto yy123;
	}
yy130:
	++in->cur;
yyFillLabel50:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 50;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'T':
	case 't':	goto yy142;
	default:	goto yy123;
	}
yy131:
	++in->cur;
yyFillLabel51:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 51;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'E':
	case 'e':	goto yy143;
	default:	goto yy123;
	}
yy132:
	++in->cur;
yyFillLabel52:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 52;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'A':
	case 'a':	goto yy144;
	default:	goto yy123;
	}
yy133:
	++in->cur;
yyFillLabel53:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 53;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'E':
	case 'e':	goto yy145;
	default:	goto yy123;
	}
yy134:
	++in->cur;
	{ result = POP_UNKNOWN; break; }
yy136:
	++in->cur;
yyFillLabel54:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 54;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'A':
	case 'a':	goto yy146;
	default:	goto yy123;
	}
yy137:
	++in->cur;
yyFillLabel55:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 55;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'E':
	case 'e':	goto yy148;
	default:	goto yy123;
	}
yy138:
	++in->cur;
yyFillLabel56:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 56;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'T':
	case 't':	goto yy149;
	default:	goto yy123;
	}
yy139:
	++in->cur;
yyFillLabel57:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 57;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'P':
	case 'p':	goto yy150;
	default:	goto yy123;
	}
yy140:
	++in->cur;
yyFillLabel58:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 58;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'S':
	case 's':	goto yy152;
	default:	goto yy123;
	}
yy141:
	++in->cur;
yyFillLabel59:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 59;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'T':
	case 't':	goto yy153;
	default:	goto yy123;
	}
yy142:
	++in->cur;
yyFillLabel60:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 60;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'R':
	case 'r':	goto yy155;
	default:	goto yy123;
	}
yy143:
	++in->cur;
yyFillLabel61:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 61;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'T':
	case 't':	goto yy156;
	default:	goto yy123;
	}
yy144:
	++in->cur;
yyFillLabel62:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 62;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'T':
	case 't':	goto yy158;
	default:	goto yy123;
	}
yy145:
	++in->cur;
yyFillLabel63:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 63;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case 'R':
	case 'r':	goto yy160;
	default:	goto yy123;
	}
yy146:
	++in->cur;
yyFillLabel64:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy161;
	case ' ':	goto yy146;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 64;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy148:
	++in->cur;
yyFillLabel65:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 65;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:	goto yy163;
	}
yy149:
	++in->cur;
yyFillLabel66:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 66;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:	goto yy166;
	}
yy150:
	++in->cur;
yyFillLabel67:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy167;
	case ' ':	goto yy150;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 67;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy152:
	++in->cur;
yyFillLabel68:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 68;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:	goto yy169;
	}
yy153:
	++in->cur;
yyFillLabel69:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy170;
	case ' ':	goto yy153;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 69;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy155:
	++in->cur;
yyFillLabel70:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 70;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:	goto yy172;
	}
yy156:
	++in->cur;
yyFillLabel71:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy173;
	case ' ':	goto yy156;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 71;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy158:
	++in->cur;
yyFillLabel72:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy174;
	case ' ':	goto yy158;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 72;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy160:
	++in->cur;
yyFillLabel73:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 73;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:	goto yy176;
	}
yy161:
	++in->cur;
yyFillLabel74:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy177;
	default:
		if (in->lim <= in->cur) {
			in->state = 74;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy162:
	++in->cur;
yyFillLabel75:
	yych = *in->cur;
yy163:
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':	goto yy162;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy179;
	default:
		if (in->lim <= in->cur) {
			in->state = 75;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy164:
	++in->cur;
yyFillLabel76:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy181;
	default:
		if (in->lim <= in->cur) {
			in->state = 76;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy165:
	++in->cur;
yyFillLabel77:
	yych = *in->cur;
yy166:
	switch (yych) {
	case '\r':	goto yy164;
	case ' ':	goto yy165;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy183;
	default:
		if (in->lim <= in->cur) {
			in->state = 77;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy167:
	++in->cur;
yyFillLabel78:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy185;
	default:
		if (in->lim <= in->cur) {
			in->state = 78;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy168:
	++in->cur;
yyFillLabel79:
	yych = *in->cur;
yy169:
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':	goto yy168;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy187;
	default:
		if (in->lim <= in->cur) {
			in->state = 79;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy170:
	++in->cur;
yyFillLabel80:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy189;
	default:
		if (in->lim <= in->cur) {
			in->state = 80;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy171:
	++in->cur;
yyFillLabel81:
	yych = *in->cur;
yy172:
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':	goto yy171;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy191;
	default:
		if (in->lim <= in->cur) {
			in->state = 81;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy173:
	++in->cur;
yyFillLabel82:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy193;
	default:
		if (in->lim <= in->cur) {
			in->state = 82;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy174:
	++in->cur;
yyFillLabel83:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy195;
	default:
		if (in->lim <= in->cur) {
			in->state = 83;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy175:
	++in->cur;
yyFillLabel84:
	yych = *in->cur;
yy176:
	switch (yych) {
	case '\r':	goto yy120;
	case ' ':	goto yy175;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		yyt1 = in->cur;
		goto yy197;
	default:
		if (in->lim <= in->cur) {
			in->state = 84;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy177:
	++in->cur;
	{ result = POP_CAPA; break; }
yy179:
	++in->cur;
yyFillLabel85:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy199;
	case ' ':	goto yy200;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy179;
	default:
		if (in->lim <= in->cur) {
			in->state = 85;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy181:
	++in->cur;
	{ result = POP_LIST; break; }
yy183:
	++in->cur;
yyFillLabel86:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy202;
	case ' ':	goto yy203;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy183;
	default:
		if (in->lim <= in->cur) {
			in->state = 86;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy185:
	++in->cur;
	{ result = POP_NOOP; break; }
yy187:
	++in->cur;
yyFillLabel87:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy205;
	case ' ':	goto yy206;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy187;
	default:
		if (in->lim <= in->cur) {
			in->state = 87;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy189:
	++in->cur;
	{ result = POP_QUIT; break; }
yy191:
	++in->cur;
yyFillLabel88:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy208;
	case ' ':	goto yy209;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy191;
	default:
		if (in->lim <= in->cur) {
			in->state = 88;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy193:
	++in->cur;
	{ result = POP_RSET; break; }
yy195:
	++in->cur;
	{ result = POP_STAT; break; }
yy197:
	++in->cur;
yyFillLabel89:
	yych = *in->cur;
	switch (yych) {
	case '\r':
		yyt2 = in->cur;
		goto yy211;
	case ' ':
		yyt2 = in->cur;
		goto yy212;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy197;
	default:
		if (in->lim <= in->cur) {
			in->state = 89;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy199:
	++in->cur;
yyFillLabel90:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy214;
	default:
		if (in->lim <= in->cur) {
			in->state = 90;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy200:
	++in->cur;
yyFillLabel91:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy199;
	case ' ':	goto yy200;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 91;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy202:
	++in->cur;
yyFillLabel92:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy216;
	default:
		if (in->lim <= in->cur) {
			in->state = 92;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy203:
	++in->cur;
yyFillLabel93:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy202;
	case ' ':	goto yy203;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 93;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy205:
	++in->cur;
yyFillLabel94:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy218;
	default:
		if (in->lim <= in->cur) {
			in->state = 94;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy206:
	++in->cur;
yyFillLabel95:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy205;
	case ' ':	goto yy206;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 95;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy208:
	++in->cur;
yyFillLabel96:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy220;
	default:
		if (in->lim <= in->cur) {
			in->state = 96;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy209:
	++in->cur;
yyFillLabel97:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy208;
	case ' ':	goto yy209;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 97;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy211:
	++in->cur;
yyFillLabel98:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy222;
	default:
		if (in->lim <= in->cur) {
			in->state = 98;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy212:
	++in->cur;
yyFillLabel99:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy211;
	case ' ':	goto yy212;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy122;
	default:
		if (in->lim <= in->cur) {
			in->state = 99;
			{ return POP_INCOMPLETE; }
		}
		goto yy121;
	}
yy214:
	++in->cur;
	{ result = POP_DELE; break; }
yy216:
	++in->cur;
	{ result = POP_LIST_MSG; break; }
yy218:
	++in->cur;
	{ result = POP_PASS; break; }
yy220:
	++in->cur;
	{ result = POP_RETR; break; }
yy222:
	++in->cur;
	args = yyt1;
	arge = yyt2;
	{ result = POP_USER; break; }
yy224:
	{ result = POP_INCOMPLETE; break; }

	}

	end = in->cur;
	*arg = args;
	*argLen = arge - args;
	*len = end - in->tok;
	in->state = -1;
	return result;
}