/* Generated by re2c 2.2 */
#include "logger.h"
#include "pop3.h"
#include <stddef.h>
#include <string.h>




#define COPY                                                                                                           \
	do                                                                                                                 \
	{                                                                                                                  \
		memcpy(&in->writeBuf[in->written], in->tok, in->cur - in->tok);                                                \
		in->written += in->cur - in->tok;                                                                              \
	} while (0)

bool destuffMail(Input *in)
{
	char yych;
	bool result;

#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy0;
case 0:
	if (in->lim <= in->cur) goto yy15;
	goto yyFillLabel0;
case 1:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel1;
case 2:
	if (in->lim <= in->cur) goto yy4;
	goto yyFillLabel2;
case 3:
	if (in->lim <= in->cur) goto yy10;
	goto yyFillLabel3;
case 4:
	if (in->lim <= in->cur) goto yy26;
	goto yyFillLabel4;
case 5:
	if (in->lim <= in->cur) goto yy20;
	goto yyFillLabel5;
case 6:
	if (in->lim <= in->cur) goto yy22;
	goto yyFillLabel6;
}

#undef YYGETSTATE

	for (;;)
	{
		in->tok = in->mar = in->cur;
		

yy0:
	switch (in->cond) {
	case yycbegin:
		goto yyc_begin;
	case yycline:
		goto yyc_line;
	}
/* *********************************** */
yyc_begin:
yyFillLabel0:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy5;
	case '.':	goto yy6;
	default:
		if (in->lim <= in->cur) {
			in->state = 0;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy3;
	}
yy3:
	++in->cur;
yy4:
	in->cond = yycline;
	{ COPY; continue; }
yy5:
	++in->cur;
yyFillLabel1:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy7;
	default:
		if (in->lim <= in->cur) {
			in->state = 1;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy4;
	}
yy6:
	in->mar = ++in->cur;
yyFillLabel2:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy9;
	case '.':	goto yy11;
	default:
		if (in->lim <= in->cur) {
			in->state = 2;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy4;
	}
yy7:
	++in->cur;
	{ COPY; continue; }
yy9:
	++in->cur;
yyFillLabel3:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy13;
	default:
		if (in->lim <= in->cur) {
			in->state = 3;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy10;
	}
yy10:
	in->cur = in->mar;
	goto yy4;
yy11:
	++in->cur;
	in->cond = yycline;
	{ in->writeBuf[in->written++] = '.'; continue; }
yy13:
	++in->cur;
	{ result = true; break; }
yy15:
	{ result = true; break; }
/* *********************************** */
yyc_line:
yyFillLabel4:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy21;
	case '\r':	goto yy23;
	default:
		if (in->lim <= in->cur) {
			in->state = 4;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy18;
	}
yy18:
	++in->cur;
yyFillLabel5:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy20;
	default:
		if (in->lim <= in->cur) {
			in->state = 5;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy18;
	}
yy20:
	{ COPY; continue; }
yy21:
	++in->cur;
yy22:
	{ COPY; continue; }
yy23:
	++in->cur;
yyFillLabel6:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy24;
	default:
		if (in->lim <= in->cur) {
			in->state = 6;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy22;
	}
yy24:
	++in->cur;
	in->cond = yycbegin;
	{ COPY; continue; }
yy26:
	{ result = true; break; }

	}

	in->state = -1;
	return result;
}

bool stuffMail(Input *in)
{
	char yych;
	bool result;

#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy27;
case 7:
	if (in->lim <= in->cur) goto yy37;
	goto yyFillLabel7;
case 8:
	if (in->lim <= in->cur) goto yy31;
	goto yyFillLabel8;
case 9:
	if (in->lim <= in->cur) goto yy48;
	goto yyFillLabel9;
case 10:
	if (in->lim <= in->cur) goto yy42;
	goto yyFillLabel10;
case 11:
	if (in->lim <= in->cur) goto yy44;
	goto yyFillLabel11;
}

#undef YYGETSTATE

	for (;;)
	{
		in->tok = in->mar = in->cur;
		

yy27:
	switch (in->cond) {
	case yycbegin:
		goto yyc_begin;
	case yycline:
		goto yyc_line;
	}
/* *********************************** */
yyc_begin:
yyFillLabel7:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy32;
	case '.':	goto yy33;
	default:
		if (in->lim <= in->cur) {
			in->state = 7;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy30;
	}
yy30:
	++in->cur;
yy31:
	in->cond = yycline;
	{ COPY; continue; }
yy32:
	++in->cur;
yyFillLabel8:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy35;
	default:
		if (in->lim <= in->cur) {
			in->state = 8;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy31;
	}
yy33:
	++in->cur;
	in->cond = yycline;
	{ in->writeBuf[in->written++] = '.'; in->writeBuf[in->written++] = '.'; continue; }
yy35:
	++in->cur;
	{ COPY; continue; }
yy37:
	{ char str[] = ".\r\n"; memcpy(&in->writeBuf[in->written], str, sizeof(str) - 1); in->written += sizeof(str) - 1; result = true; break; }
/* *********************************** */
yyc_line:
yyFillLabel9:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy43;
	case '\r':	goto yy45;
	default:
		if (in->lim <= in->cur) {
			in->state = 9;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy40;
	}
yy40:
	++in->cur;
yyFillLabel10:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy42;
	default:
		if (in->lim <= in->cur) {
			in->state = 10;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy40;
	}
yy42:
	{ COPY; continue; }
yy43:
	++in->cur;
yy44:
	{ COPY; continue; }
yy45:
	++in->cur;
yyFillLabel11:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy46;
	default:
		if (in->lim <= in->cur) {
			in->state = 11;
			{ if(in->cond == yycline) { COPY; in->tok = in->mar = in->cur; } return false; }
		}
		goto yy44;
	}
yy46:
	++in->cur;
	in->cond = yycbegin;
	{ COPY; continue; }
yy48:
	{ char str[] = ".\r\n"; memcpy(&in->writeBuf[in->written], str, sizeof(str) - 1); in->written += sizeof(str) - 1; result = true; break; }

	}

	in->state = -1;
	return result;
}

bool parsePopResponse(Input *in, bool multiline)
{
	char yych;
	bool result;

#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy49;
case 12:
	if (in->lim <= in->cur) goto yy64;
	goto yyFillLabel12;
case 13:
	if (in->lim <= in->cur) goto yy53;
	goto yyFillLabel13;
case 14:
	if (in->lim <= in->cur) goto yy53;
	goto yyFillLabel14;
case 15:
	if (in->lim <= in->cur) goto yy57;
	goto yyFillLabel15;
case 16:
	if (in->lim <= in->cur) goto yy57;
	goto yyFillLabel16;
case 17:
	if (in->lim <= in->cur) goto yy57;
	goto yyFillLabel17;
case 18:
	if (in->lim <= in->cur) goto yy75;
	goto yyFillLabel18;
case 19:
	if (in->lim <= in->cur) goto yy69;
	goto yyFillLabel19;
case 20:
	if (in->lim <= in->cur) goto yy71;
	goto yyFillLabel20;
case 21:
	if (in->lim <= in->cur) goto yy90;
	goto yyFillLabel21;
case 22:
	if (in->lim <= in->cur) goto yy80;
	goto yyFillLabel22;
case 23:
	if (in->lim <= in->cur) goto yy82;
	goto yyFillLabel23;
case 24:
	if (in->lim <= in->cur) goto yy85;
	goto yyFillLabel24;
case 25:
	if (in->lim <= in->cur) goto yy85;
	goto yyFillLabel25;
case 26:
	if (in->lim <= in->cur) goto yy85;
	goto yyFillLabel26;
}

#undef YYGETSTATE

	for (;;)
	{
		in->tok = in->mar = in->cur;
		

yy49:
	switch (in->cond) {
	case yycstatus:
		goto yyc_status;
	case yycmsg:
		goto yyc_msg;
	case yycextra:
		goto yyc_extra;
	}
/* *********************************** */
yyc_status:
yyFillLabel12:
	yych = *in->cur;
	switch (yych) {
	case '+':	goto yy54;
	case '-':	goto yy55;
	default:
		if (in->lim <= in->cur) {
			in->state = 12;
			{ return false; }
		}
		goto yy52;
	}
yy52:
	++in->cur;
yy53:
	{ char str[] = "-ERR Invalid response from origin\r\n"; memcpy(&in->writeBuf[in->written], str, sizeof(str) - 1); in->written += sizeof(str) - 1; result = true; break; }
yy54:
	in->mar = ++in->cur;
yyFillLabel13:
	yych = *in->cur;
	switch (yych) {
	case 'O':	goto yy56;
	default:
		if (in->lim <= in->cur) {
			in->state = 13;
			{ return false; }
		}
		goto yy53;
	}
yy55:
	in->mar = ++in->cur;
yyFillLabel14:
	yych = *in->cur;
	switch (yych) {
	case 'E':	goto yy58;
	default:
		if (in->lim <= in->cur) {
			in->state = 14;
			{ return false; }
		}
		goto yy53;
	}
yy56:
	++in->cur;
yyFillLabel15:
	yych = *in->cur;
	switch (yych) {
	case 'K':	goto yy59;
	default:
		if (in->lim <= in->cur) {
			in->state = 15;
			{ return false; }
		}
		goto yy57;
	}
yy57:
	in->cur = in->mar;
	goto yy53;
yy58:
	++in->cur;
yyFillLabel16:
	yych = *in->cur;
	switch (yych) {
	case 'R':	goto yy61;
	default:
		if (in->lim <= in->cur) {
			in->state = 16;
			{ return false; }
		}
		goto yy57;
	}
yy59:
	++in->cur;
	in->cond = yycmsg;
	{ COPY; continue; }
yy61:
	++in->cur;
yyFillLabel17:
	yych = *in->cur;
	switch (yych) {
	case 'R':	goto yy62;
	default:
		if (in->lim <= in->cur) {
			in->state = 17;
			{ return false; }
		}
		goto yy57;
	}
yy62:
	++in->cur;
	in->cond = yycmsg;
	{ COPY; continue; }
yy64:
	{ result = true; break; }
/* *********************************** */
yyc_msg:
yyFillLabel18:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy70;
	case '\r':	goto yy72;
	default:
		if (in->lim <= in->cur) {
			in->state = 18;
			{ return false; }
		}
		goto yy67;
	}
yy67:
	++in->cur;
yyFillLabel19:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy69;
	default:
		if (in->lim <= in->cur) {
			in->state = 19;
			{ return false; }
		}
		goto yy67;
	}
yy69:
	{ COPY; continue; }
yy70:
	++in->cur;
yy71:
	{ COPY; continue; }
yy72:
	++in->cur;
yyFillLabel20:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy73;
	default:
		if (in->lim <= in->cur) {
			in->state = 20;
			{ return false; }
		}
		goto yy71;
	}
yy73:
	++in->cur;
	{ COPY; if(multiline) { in->cond = yycextra; continue; } else { result = true; break; } }
yy75:
	{ result = true; break; }
/* *********************************** */
yyc_extra:
yyFillLabel21:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy81;
	case '\r':	goto yy83;
	default:
		if (in->lim <= in->cur) {
			in->state = 21;
			{ return false; }
		}
		goto yy78;
	}
yy78:
	++in->cur;
yyFillLabel22:
	yych = *in->cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	default:
		if (in->lim <= in->cur) {
			in->state = 22;
			{ return false; }
		}
		goto yy78;
	}
yy80:
	{ COPY; continue; }
yy81:
	++in->cur;
yy82:
	{ COPY; continue; }
yy83:
	in->mar = ++in->cur;
yyFillLabel23:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy84;
	default:
		if (in->lim <= in->cur) {
			in->state = 23;
			{ return false; }
		}
		goto yy82;
	}
yy84:
	++in->cur;
yyFillLabel24:
	yych = *in->cur;
	switch (yych) {
	case '.':	goto yy86;
	default:
		if (in->lim <= in->cur) {
			in->state = 24;
			{ return false; }
		}
		goto yy85;
	}
yy85:
	in->cur = in->mar;
	goto yy82;
yy86:
	++in->cur;
yyFillLabel25:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy87;
	default:
		if (in->lim <= in->cur) {
			in->state = 25;
			{ return false; }
		}
		goto yy85;
	}
yy87:
	++in->cur;
yyFillLabel26:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy88;
	default:
		if (in->lim <= in->cur) {
			in->state = 26;
			{ return false; }
		}
		goto yy85;
	}
yy88:
	++in->cur;
	{ COPY; result = true; break; }
yy90:
	{ result = true; break; }

	}

	in->tok = in->mar = in->cur;
	in->state = -1;
	in->cond = yycstatus;
	return result;
}

PopCommand parsePopRequest(Input *in, char **arg, size_t *argLen, size_t *len)
{
	char yych;
	char *args = NULL, *arge = NULL, *end;
	PopCommand result;
	char *yyt1;
char *yyt2;


#define YYGETSTATE in->state
switch (YYGETSTATE) {
default:
	goto yy91;
case 27:
	if (in->lim <= in->cur) goto yy132;
	goto yyFillLabel27;
case 28:
	if (in->lim <= in->cur) goto yy95;
	goto yyFillLabel28;
case 29:
	if (in->lim <= in->cur) goto yy95;
	goto yyFillLabel29;
case 30:
	if (in->lim <= in->cur) goto yy95;
	goto yyFillLabel30;
case 31:
	if (in->lim <= in->cur) goto yy95;
	goto yyFillLabel31;
case 32:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel32;
case 33:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel33;
case 34:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel34;
case 35:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel35;
case 36:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel36;
case 37:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel37;
case 38:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel38;
case 39:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel39;
case 40:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel40;
case 41:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel41;
case 42:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel42;
case 43:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel43;
case 44:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel44;
case 45:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel45;
case 46:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel46;
case 47:
	if (in->lim <= in->cur) goto yy103;
	goto yyFillLabel47;
}

#undef YYGETSTATE

	for (;;)
	{
		

yy91:
yyFillLabel27:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy96;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'S':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy97;
	case 'R':
	case 'r':	goto yy98;
	case 'U':
	case 'u':	goto yy99;
	default:
		if (in->lim <= in->cur) {
			in->state = 27;
			{ return POP_INCOMPLETE; }
		}
		goto yy94;
	}
yy94:
	++in->cur;
yy95:
	{ result = POP_INVALID; break; }
yy96:
	++in->cur;
yyFillLabel28:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy100;
	default:
		if (in->lim <= in->cur) {
			in->state = 28;
			{ return POP_INCOMPLETE; }
		}
		goto yy95;
	}
yy97:
	in->mar = ++in->cur;
yyFillLabel29:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy102;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	default:
		if (in->lim <= in->cur) {
			in->state = 29;
			{ return POP_INCOMPLETE; }
		}
		goto yy95;
	}
yy98:
	in->mar = ++in->cur;
yyFillLabel30:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy102;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	case 'E':
	case 'e':	goto yy106;
	default:
		if (in->lim <= in->cur) {
			in->state = 30;
			{ return POP_INCOMPLETE; }
		}
		goto yy95;
	}
yy99:
	in->mar = ++in->cur;
yyFillLabel31:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy102;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	case 'S':
	case 's':	goto yy107;
	default:
		if (in->lim <= in->cur) {
			in->state = 31;
			{ return POP_INCOMPLETE; }
		}
		goto yy95;
	}
yy100:
	++in->cur;
	{ result = POP_INVALID; break; }
yy102:
	++in->cur;
yyFillLabel32:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy108;
	default:
		if (in->lim <= in->cur) {
			in->state = 32;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy103:
	in->cur = in->mar;
	goto yy95;
yy104:
	++in->cur;
yyFillLabel33:
	yych = *in->cur;
yy105:
	switch (yych) {
	case '\r':	goto yy102;
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	default:
		if (in->lim <= in->cur) {
			in->state = 33;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy106:
	++in->cur;
yyFillLabel34:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 34;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	case 'T':
	case 't':	goto yy110;
	default:	goto yy105;
	}
yy107:
	++in->cur;
yyFillLabel35:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 35;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	case 'E':
	case 'e':	goto yy111;
	default:	goto yy105;
	}
yy108:
	++in->cur;
	{ result = POP_UNKNOWN; break; }
yy110:
	++in->cur;
yyFillLabel36:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 36;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	case 'R':
	case 'r':	goto yy112;
	default:	goto yy105;
	}
yy111:
	++in->cur;
yyFillLabel37:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 37;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	case 'R':
	case 'r':	goto yy113;
	default:	goto yy105;
	}
yy112:
	++in->cur;
yyFillLabel38:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 38;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	default:	goto yy115;
	}
yy113:
	++in->cur;
yyFillLabel39:
	yych = *in->cur;
	switch (yych) {
	case 0x00:
		if (in->lim <= in->cur) {
			in->state = 39;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	default:	goto yy117;
	}
yy114:
	++in->cur;
yyFillLabel40:
	yych = *in->cur;
yy115:
	switch (yych) {
	case '\r':	goto yy102;
	case ' ':	goto yy114;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy118;
	default:
		if (in->lim <= in->cur) {
			in->state = 40;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy116:
	++in->cur;
yyFillLabel41:
	yych = *in->cur;
yy117:
	switch (yych) {
	case '\r':	goto yy102;
	case ' ':	goto yy116;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		yyt1 = in->cur;
		goto yy120;
	default:
		if (in->lim <= in->cur) {
			in->state = 41;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy118:
	++in->cur;
yyFillLabel42:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy122;
	case ' ':	goto yy123;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy118;
	default:
		if (in->lim <= in->cur) {
			in->state = 42;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy120:
	++in->cur;
yyFillLabel43:
	yych = *in->cur;
	switch (yych) {
	case '\r':
		yyt2 = in->cur;
		goto yy125;
	case ' ':
		yyt2 = in->cur;
		goto yy126;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy120;
	default:
		if (in->lim <= in->cur) {
			in->state = 43;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy122:
	++in->cur;
yyFillLabel44:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy128;
	default:
		if (in->lim <= in->cur) {
			in->state = 44;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy123:
	++in->cur;
yyFillLabel45:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy122;
	case ' ':	goto yy123;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	default:
		if (in->lim <= in->cur) {
			in->state = 45;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy125:
	++in->cur;
yyFillLabel46:
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy130;
	default:
		if (in->lim <= in->cur) {
			in->state = 46;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy126:
	++in->cur;
yyFillLabel47:
	yych = *in->cur;
	switch (yych) {
	case '\r':	goto yy125;
	case ' ':	goto yy126;
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy104;
	default:
		if (in->lim <= in->cur) {
			in->state = 47;
			{ return POP_INCOMPLETE; }
		}
		goto yy103;
	}
yy128:
	++in->cur;
	{ result = POP_RETR; break; }
yy130:
	++in->cur;
	args = yyt1;
	arge = yyt2;
	{ result = POP_USER; break; }
yy132:
	{ result = POP_INCOMPLETE; break; }

	}

	end = in->cur;
	*arg = args;
	*argLen = arge - args;
	*len = end - in->tok;
	in->state = -1;
	return result;
}