/* Generated by re2c 2.2 */

#pragma once
#include <stddef.h>
typedef struct
{
	char *lim, *cur, *mar, *tok;
	char *buf, *writeBuf;
	int state, cond;
	size_t written, bufSize;
	char *yyt1;
char *yyt2;

} Input;

#include "pop3/pop3.h"
bool stuffMail(Input *in);
bool destuffMail(Input *in);
bool parsePopResponse(Input *in, bool multiline, bool *success);
PopCommand parsePopRequest(Input *in, char **arg, size_t *argLen, size_t *len);

enum YYCONDTYPE {
	yycbegin,
	yycline,
	yycstatus,
	yycmsg_err,
	yycmsg_ok,
	yycextra,
};
